### ISSUE TITLE
Wither + Blaze Hostility

### ISSUE THREAD

**Issue by Savilyn** [TheUltiOne/WitherOrigins2#1]
Hey! I really enjoy the Origin, I'm trying to get it working on a server some friends and I play on but I'm having trouble with the hostility. Wither Skeletons and Blazes attack me at random, here's some instances that I ran into:

- A Wither Skeleton and Blaze stopped attacking me after I hit it a few times with a sword.
- A Wither Skeleton lost interest in attacking after I blocked it a few times with a shield.
- Wither Skeletons and Blazes will attack shortly after I spawn them. When I run far enough to lose their interest and come back, they usually don't aggro.
- While fighting some blazes off, a Wither Skeleton that was previously neutral towards me started to attack.

**Comment by TheUltiOne** [comment]
Omfg I forgot to update the GitHub. Sorry

**Comment by TheUltiOne** [comment]
I’ll fix this issue soon, ASAP

hostility has been the hardest part for me ;P

**Comment by Savilyn** [comment]
All good! I've noticed hostility is a tricky one even with some of the original origins. Thank you for taking the time to try and figure it out!

**Comment by TheUltiOne** [comment]
I finally updated this, sorry if you stopped using this.

This repo will be archived, consider [this repository instead](https://github.com/TheUltiOne/WitherOrigins)
